// 'Regular' species.
#define SPECIES_HUMAN			"Human"
#define SPECIES_EXALT_HUMAN		"Exalt Human"
#define SPECIES_HUMAN_VATBORN	"Vatborn"
#define SPECIES_UNATHI			"Lizard"
#define SPECIES_SKRELL			"Mar'qua"
#define SPECIES_TESHARI			"Raptid"
#define SPECIES_TAJ				"Sablekyne"
#define SPECIES_PROMETHEAN		"Promethean"
#define SPECIES_DIONA			"Diona"
#define SPECIES_VOX				"Vox"

#define SPECIES_AKULA			"Akula"
#define SPECIES_ALRAUNE			"Seelie"
#define SPECIES_NEVREAN			"Avian"
#define SPECIES_PROTEAN			"Protean"
#define SPECIES_RAPALA			"Harpy"
#define SPECIES_NARAMAD			"Naramad"
#define SPECIES_VASILISSAN		"Cht'Mant"
#define SPECIES_VULPKANIN		"Fox"
#define SPECIES_XENOCHIMERA		"Xenochimera"
#define SPECIES_XENOHYBRID		"Xenomorph Hybrid"
#define SPECIES_ZORREN_FLAT		"Dog"
#define SPECIES_ZORREN_HIGH		"Wolf"
#define SPECIES_STATIONXENO     "Xenomorph Hybrid"
#define SPECIES_SLIME			"Aulvae"
#define SPECIES_CUSTOM			"Custom Species"

// Monkey and alien monkeys.
#define SPECIES_MONKEY			"Monkey"
#define SPECIES_MONKEY_TAJ		"Farwa"
#define SPECIES_MONKEY_SKRELL	"Neaera"
#define SPECIES_MONKEY_UNATHI	"Stok"

// Virtual Reality IDs.
#define SPECIES_VR				"Virtual Reality Avatar"
#define SPECIES_VR_HUMAN		"Virtual Reality Human"
#define SPECIES_VR_UNATHI		"Virtual Reality Lizard"
#define SPECIES_VR_TAJ			"Virtual Reality Sablekyne" // NO CHANGING.
#define SPECIES_VR_SKRELL		"Virtual Reality Mar'qua"
#define SPECIES_VR_TESHARI		"Virtual Reality Raptid"
//#define SPECIES_VR_DIONA		"Virtual Reality Diona"

// Ayyy IDs.
#define SPECIES_XENO			"Xenomorph"
#define SPECIES_XENO_DRONE		"Xenomorph Drone"
#define SPECIES_XENO_HUNTER		"Xenomorph Hunter"
#define SPECIES_XENO_SENTINEL	"Xenomorph Sentinel"
#define SPECIES_XENO_QUEEN		"Xenomorph Queen"

// Misc species. Mostly unused but might as well be complete.
#define SPECIES_SHADOW			"Shadow"
#define SPECIES_SKELETON		"Skeleton"
#define SPECIES_GOLEM			"Golem"
#define SPECIES_EVENT1			"X Occursus"

// Forms for the Appearances
#define FORM_HUMAN				"Human"
#define FORM_EXALT_HUMAN		"Exalt Human"
#define FORM_CANINE				"Canine"
#define FORM_FELINE				"Feline"
#define FORM_SHARK				"Shark"
#define FORM_SUDAK				"Shark (Snoutless)"
#define FORM_LIZARD				"Lizard"
#define FORM_LIZARD_TGSHARP     "Sharp-Snouted Lizard"
#define FORM_LIZARD_TGSMOOTH    "Smooth-Snouted Lizard"
#define FORM_VULPINE			"Vulpine"
#define FORM_FENNEC				"Fennec"
#define FORM_MOTH				"Moth"
#define FORM_MOTH_WHITE			"Moth (Colorable)"
#define FORM_NARAMAD			"Naramad"
#define FORM_SLIME				"Aulvae"
#define FORM_AVIAN				"Avian"
#define FORM_SPIDER				"Arachnoid"
#define FORM_STATIONXENO	    "Xenohybrid Drone"
#define FORM_STATIONXENO_HUNTER	"Xenohybrid Hunter"
#define FORM_STATIONXENO_QUEEN	"Xenohybrid Queen"
#define FORM_STATIONXENO_SENTI  "Xenohybrid Sentinel"
#define FORM_SABLEKYNE			"Sablekyne"
#define FORM_MARQUA				"Mar'Qua"
#define FORM_KRIOSAN  			"Kriosan"
#define FORM_AKULA				"Akula"
#define FORM_CHTMANT			"Cht'mant"
#define FORM_CINDAR				"Cindarite"
#define FORM_OPIFEX				"Opifex"
#define FORM_SOTSYNTH			"Soteria Synthetic"
#define FORM_AGSYNTH			"Artificer Guild Synthetic"
#define FORM_BSSYNTH			"Blackshield Synthetic"
#define FORM_CHURCHSYNTH		"Absolute Synthetic"
#define FORM_NASHEF				"Nashef-Agunabi"
#define FORM_FBP				"Full Body Prosthetic"
#define FORM_UNBRANDED			"Unbranded Full Body Prosthetic"
#define FORM_FOLKEN				"Folken"
#define FORM_MYCUS				"Mycus"
#define FORM_AXOLOTL			"Axolotl"

#define FORM_BIRD				"Avian"

#define FORM_VOX				"Vox"
#define FORM_VOX_AZURE			"Azure Vox"
#define FORM_VOX_BROWN			"Brown Vox"
#define FORM_VOX_EMERALD		"Emerald Vox"
#define FORM_VOX_GRAY			"Gray Vox"
#define FORM_VOX_LIME			"Lime Vox"

#define FORM_VOX_BONEY			"Bony Vox"
#define FORM_VOX_TECHY			"Techy Vox"

//
#define FORM_MONKEY				"Monkey"
#define FORM_GOLEM				"Golem"
//#define FORM_HIVEMIND			"Hivelord" - we defeated you >:T
#define FORM_ALIEN_DRONE		"Xenomorph Drone"
#define FORM_ALIEN_SENTINEL		"Xenomorph Sentinel"
#define FORM_ALIEN_HUNTER		"Xenomorph Hunter"
#define FORM_ALIEN_QUEEN		"Xenomorph Queen"
