/datum/trade_station/station_ghostkitchen
	name_pool = list(
		"GK 'Spector'" = "Ghost Kitchen 'Spector': \"We got tons of orders that need filling, will take anything you can cook."
	)
	uid = "ghostkitchen"
	tree_x = 0.5
	tree_y = 0.9
	start_discovered = TRUE
	spawn_always = TRUE
	markup = 10 //These guys should only want to buy food never sell, so this dosnt matter.
	offer_limit = 20
	base_income = 0
	wealth = 0
	regain_stock = FALSE
	hidden_inv_threshold = 2000
	recommendation_threshold = 300
	icon_states = list("nt_cruiser", "object")
	stations_recommended = list("mcronalds", "botany") //Alt way to get to it
	inventory = list(
		"Office Supplies" = list(
			/obj/item/pen = good_data("Pen", list(5, 20), 25),
			/obj/item/pen/multi = good_data("Multi Color", list(5, 20), 75),
			/obj/item/paper_bin = good_data("Paper Bin", list(5, 20), 100),
			/obj/item/device/lighting/toggleable/lamp = good_data("Desk Lamp", list(5, 20), 100),
			/obj/item/storage/briefcase = good_data("Briefcase", list(5, 20), 500), //Rather pricy, but it's to dissuade using them for storage reasons. It's a FASHION statement, sweaty! -Wilson
			/obj/item/storage/secure/briefcase = good_data("Secure Briefcase", list(5, 20), 550),
			/obj/item/toy/desk/dippingbird/branded = good_data("Spector Dipping Bird Model", list(5, 20), 75)
		),
		"Non-Meals" = list(
			/obj/item/reagent_containers/snacks/rawcutlet = good_data("Raw Cutlet", list(-100, -50), 5),
			/obj/item/reagent_containers/snacks/cutlet = good_data("Cooked Cutlet", list(-100, -50), 7),
			/obj/item/reagent_containers/snacks/patty_raw = good_data("Raw Patty", list(-100, -50), 6),
			/obj/item/reagent_containers/snacks/patty = good_data("Cooked Patty", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/chickenbreast = good_data("Chicken Breast", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/rawmeatball = good_data("Raw Meatball", list(-100, -50), 7),
			/obj/item/reagent_containers/snacks/meatball = good_data("Meatball", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/rawsticks = good_data("Raw Potato Sticks", list(-100, -50), 4),
			/obj/item/reagent_containers/snacks/tofubread = good_data("Tofubread", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/tofubreadslice = good_data("Tofubread Slice", list(-100, -50), 2),
			/obj/item/reagent_containers/snacks/tofu = good_data("Tofu", list(-100, -50), 4),
			/obj/item/reagent_containers/snacks/stuffing = good_data("Stuffing", list(-100, -50), 18),
			/obj/item/reagent_containers/snacks/bacon = good_data("Bacon", list(-100, -50), 7),
			/obj/item/reagent_containers/snacks/hugemushroomslice = good_data("Mushroom Slice", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/tomatomeat = good_data("Tomato Slice", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/sausage = good_data("Sausage", list(-100, -50), 28)
		),
		"Egg-Based" = list(
			/obj/item/reagent_containers/snacks/egg = good_data("Egg", list(-100, -50), 5),
			/obj/item/reagent_containers/snacks/egg/clucker = good_data("Clucker Egg", list(-100, -50), 80),
			/obj/item/reagent_containers/snacks/chocolateegg = good_data("Chocolate Egg", list(-100, -50), 12),
			/obj/item/reagent_containers/snacks/baconeggs = good_data("Egg And Bacon", list(-100, -50), 14),
			/obj/item/reagent_containers/snacks/benedict = good_data("Egg Benedict", list(-100, -50), 28),
			/obj/item/reagent_containers/snacks/muffinegg = good_data("Muffin Egg Sandwich", list(-100, -50), 35),
			/obj/item/reagent_containers/snacks/friedegg = good_data("Fried Egg", list(-100, -50), 7),
			/obj/item/reagent_containers/snacks/boiledegg = good_data("Boiled Egg", list(-100, -50), 6),
			/obj/item/reagent_containers/snacks/omelette = good_data("Omelette Du Fromage", list(-100, -50), 40)
		),
		"Breads" = list(
			/obj/item/reagent_containers/snacks/bread = good_data("Bread Loaf", list(-100, -50), 12),
			/obj/item/reagent_containers/snacks/breadslice = good_data("Bread Slice", list(-100, -50), 2),
			/obj/item/reagent_containers/snacks/creamcheesebread = good_data("Cream Cheese Bread", list(-100, -50), 18),
			/obj/item/reagent_containers/snacks/creamcheesebreadslice = good_data("Cream Cheese Bread Slice", list(-100, -50), 3),
			/obj/item/reagent_containers/snacks/meatbread = good_data("Meatbread Loaf", list(-100, -50), 20),
			/obj/item/reagent_containers/snacks/meatbreadslice = good_data("Meatbread Slice", list(-100, -50), 5),
			/obj/item/reagent_containers/snacks/bananabread = good_data("Banana-Nut Loaf", list(-100, -50), 28),
			/obj/item/reagent_containers/snacks/bananabreadslice = good_data("Banana-Nut Bread Slice", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/butterbread = good_data("Buttered Toast", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/flatbread = good_data("Flatbread", list(-100, -50), 7),
			/obj/item/reagent_containers/snacks/medialuna = good_data("Croissantt", list(-100, -50), 12),
			/obj/item/reagent_containers/snacks/dough = good_data("Dough", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/flatdough = good_data("Rolled Dough", list(-100, -50), 9),
			/obj/item/reagent_containers/snacks/doughslice = good_data("Dough slice", list(-100, -50), 4),
			/obj/item/reagent_containers/snacks/bun = good_data("Bun", list(-100, -50), 5),
			/obj/item/reagent_containers/snacks/cinnamonroll = good_data("Cinnamonroll", list(-100, -50), 18),
			/obj/item/reagent_containers/snacks/poppypretzel = good_data("Poppy Pretzel", list(-100, -50), 20),
			/obj/item/reagent_containers/snacks/cracker = good_data("Saltine", list(-100, -50), 9),
			/obj/item/reagent_containers/snacks/baguette = good_data("Baguette", list(-100, -50), 28),
			/obj/item/reagent_containers/snacks/jelliedtoast = good_data("Jillied Toast", list(-100, -50), 20),
			/obj/item/reagent_containers/snacks/jelliedtoast/cherry = good_data("Cherry Toast", list(-100, -50), 20),
			/obj/item/reagent_containers/snacks/jelliedtoast/slime = good_data("Slime Toast", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/muffin = good_data("Muffin", list(-100, -50), 10),
			/obj/item/reagent_containers/snacks/waffles = good_data("Waffles", list(-100, -50), 15)
		),
		"Sandwich" = list(
			/obj/item/reagent_containers/snacks/sandwich = good_data("Sandwich", list(-100, -50), 22),
			/obj/item/reagent_containers/snacks/toastedsandwich = good_data("Toasted Sandwich", list(-100, -50), 23),
			/obj/item/reagent_containers/snacks/toasted_guild_sandwich = good_data("Deluxe Toasted Sandwich", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/grilledcheese = good_data("Grilled Cheese", list(-100, -50), 15),
			/obj/item/reagent_containers/snacks/blt = good_data("BLT", list(-100, -50), 25),
			/obj/item/reagent_containers/snacks/twobread = good_data("Two Bread", list(-100, -50), 10),
			/obj/item/reagent_containers/snacks/jellysandwich = good_data("Jelly Sandwich", list(-100, -50), 22),
			/obj/item/reagent_containers/snacks/jellysandwich/slime = good_data("Slime Jelly Sandwich", list(-100, -50), 22),
			/obj/item/reagent_containers/snacks/jellysandwich/cherry = good_data("Cherry Jelly Sandwich", list(-100, -50), 32)
		),
		"Cakes|Pies" = list(
			/obj/item/reagent_containers/snacks/birthdaycake = good_data("Birthday Cake", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/birthdaycakeslice = good_data("Birthday Cake Slice", list(-100, -50), 20),
			/obj/item/reagent_containers/snacks/applecake = good_data("Apple Cake", list(-100, -50), 50),
			/obj/item/reagent_containers/snacks/applecakeslice = good_data("Apple Cake Slice", list(-100, -50), 10),
			/obj/item/reagent_containers/snacks/carrotcake = good_data("Carrot Cake", list(-100, -50), 50),
			/obj/item/reagent_containers/snacks/carrotcakeslice = good_data("Carrot Cake Slice", list(-100, -50), 10),
			/obj/item/reagent_containers/snacks/cheesecake = good_data("Cheese Cake", list(-100, -50), 40),
			/obj/item/reagent_containers/snacks/cheesecakeslice = good_data("Cheese Cake Slice", list(-100, -50), 8),
			/obj/item/reagent_containers/snacks/plaincake = good_data("Vanilla Cake", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/plaincakeslice = good_data("Vanilla Cake Slice", list(-100, -50), 6),
			/obj/item/reagent_containers/snacks/orangecake = good_data("Orange Cake", list(-100, -50), 50),
			/obj/item/reagent_containers/snacks/orangecakeslice = good_data("Orange Cake Slice", list(-100, -50), 10),
			/obj/item/reagent_containers/snacks/limecake = good_data("Lime Cake", list(-100, -50), 50),
			/obj/item/reagent_containers/snacks/limecakeslice = good_data("Lime Cake Slice", list(-100, -50), 10),
			/obj/item/reagent_containers/snacks/lemoncake = good_data("Lemon Cake", list(-100, -50), 50),
			/obj/item/reagent_containers/snacks/lemoncakeslice = good_data("Lemon Cake Slice", list(-100, -50), 10),
			/obj/item/reagent_containers/snacks/chocolatecake = good_data("Chocolate Cake", list(-100, -50), 70),
			/obj/item/reagent_containers/snacks/chocolatecakeslice = good_data("Chocolate Cake Slice", list(-100, -50), 12),
			/obj/item/reagent_containers/snacks/brownie = good_data("Brownie Tray", list(-100, -50), 80),
			/obj/item/reagent_containers/snacks/brownieslice = good_data("Brownie Slice", list(-100, -50), 16),
			/obj/item/reagent_containers/snacks/meatpie = good_data("Meat Pie", list(-100, -50), 90),
			/obj/item/reagent_containers/snacks/tofupie = good_data("Tofu Pie", list(-100, -50), 70),
			/obj/item/reagent_containers/snacks/amanita_pie = good_data("Amanita Pie", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/plump_pie = good_data("Plump Pie", list(-100, -50), 110),
			/obj/item/reagent_containers/snacks/applepie = good_data("Apple Piee", list(-100, -50), 90),
			/obj/item/reagent_containers/snacks/cherrypie = good_data("Cherry Pie", list(-100, -50), 90),
			/obj/item/reagent_containers/snacks/berryclafoutis = good_data("Berry Clafoutis Pie", list(-100, -50), 110),
			/obj/item/reagent_containers/snacks/pie = good_data("Pie", list(-100, -50), 70)
		),
		"Pizza!" = list(
			/obj/item/reagent_containers/snacks/pizza/margherita = good_data("Margherita Pizza", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/pizza/meatpizza = good_data("Meat Pizza", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/pizza/mushroompizza = good_data("Mushroom Pizza", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/pizza/vegetablepizza = good_data("Vegetable Pizza", list(-100, -50), 110),
			/obj/item/reagent_containers/snacks/pizza/hawaiianpizza = good_data("Hawaiian Pizza", list(-100, -50), 300),
			/obj/item/reagent_containers/snacks/hawaiianpizzaslice = good_data("Hawaiian Pizza Slice", list(-100, -50), 50),
			/obj/item/reagent_containers/snacks/vegetablepizzaslice = good_data("Vegetable Pizza Slice", list(-100, -50), 10),
			/obj/item/reagent_containers/snacks/mushroompizzaslice = good_data("Mushroom Pizza Slice", list(-100, -50), 12),
			/obj/item/reagent_containers/snacks/meatpizzaslice = good_data("Meat Pizza Slice", list(-100, -50), 15),
			/obj/item/reagent_containers/snacks/margheritaslice = good_data("Margherita Pizza Slice", list(-100, -50), 15)
		),
		"Stews" = list(
			/obj/item/reagent_containers/snacks/meatballsoup = good_data("Meatball Soup", list(-100, -50), 80),
			/obj/item/reagent_containers/snacks/slimesoup = good_data("Slime Soup", list(-100, -50), 180),
			/obj/item/reagent_containers/snacks/bloodsoup = good_data("Vampirer Soup", list(-100, -50), 60),
			/obj/item/reagent_containers/snacks/clownstears = good_data("Clown's Tears", list(-100, -50), 150),
			/obj/item/reagent_containers/snacks/vegetablesoup = good_data("Vegetable Soup", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/nettlesoup = good_data("Nettle Soup", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/mysterysoup = good_data("Vegetable Soup", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/vegetablesoup = good_data("Mystery Soup", list(-100, -50), 125),
			/obj/item/reagent_containers/snacks/wishsoup = good_data("Wish Soup", list(-100, -50), 10),
			/obj/item/reagent_containers/snacks/tomatosoup = good_data("Tomato Soup", list(-100, -50), 80),
			/obj/item/reagent_containers/snacks/mushroomsoup = good_data("Chantrelle Soup", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/beetsoup = good_data("Beet Soup", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/milosoup = good_data("Milo Soup", list(-100, -50), 140),
			/obj/item/reagent_containers/snacks/stew = good_data("Stew", list(-100, -50), 150),
			/obj/item/reagent_containers/snacks/hotchili = good_data("Hot Chili", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/coldchili = good_data("Cold Chili", list(-100, -50), 175),
			/obj/item/reagent_containers/snacks/bearchili = good_data("Bear Meat Chili", list(-100, -50), 200)
		),
		"Dairy" = list(
			/obj/item/reagent_containers/snacks/cheesewheel = good_data("Cheesewheel", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/cheesewedge = good_data("Cheese Wedge", list(-100, -50), 20),
			/obj/item/reagent_containers/snacks/butterstick = good_data("Butter Stick", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/butterslice = good_data("Butter Slice", list(-100, -50), 6),
			/obj/item/reagent_containers/snacks/icecream = good_data("Icecream", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/chocoicecream = good_data("Chocolate Icecream", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/strawberryicecream = good_data("Strawberry Icecream", list(-100, -50), 150),
			/obj/item/reagent_containers/snacks/icecreamsandwich = good_data("Icecream Sandwich", list(-100, -50), 140),
			/obj/item/reagent_containers/snacks/strawberrysandwich = good_data("Strawberry Icecream Sandwich", list(-100, -50), 150),
			/obj/item/reagent_containers/snacks/honeypudding = good_data("Honey Pudding", list(-100, -50), 180),
			/obj/item/reagent_containers/snacks/honey_icecream = good_data("Honey Icecream", list(-100, -50), 180)
		),
		"Burger" = list(
			/obj/item/reagent_containers/snacks/cheeseburger = good_data("Cheese Burger", list(-100, -50), 60),
			/obj/item/reagent_containers/snacks/monkeyburger = good_data("Monkey Meat Buger", list(-100, -50), 50),
			/obj/item/reagent_containers/snacks/fishburger = good_data("Fillet-O-Carp Sandwich", list(-100, -50), 90),
			/obj/item/reagent_containers/snacks/baconburger = good_data("Bacon Burger", list(-100, -50), 70),
			/obj/item/reagent_containers/snacks/chickenburger = good_data("Poultry Fried Steak Sandwich", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/tofuburger = good_data("Tofu Burger", list(-100, -50), 70),
			/obj/item/reagent_containers/snacks/bigbiteburger = good_data("Big Bite Burger", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/superbiteburger = good_data("Super Bite Burger", list(-100, -50), 200),
			/obj/item/reagent_containers/snacks/jellyburger = good_data("Jelly Burger", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/jellyburger/slime = good_data("Slime Jelly Burger", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/jellyburger/cherry = good_data("Cherry Jelly Burger", list(-100, -50), 120)
		),
		"Spaghetti" = list(
			/obj/item/reagent_containers/snacks/boiledspagetti= good_data("Boiled Noodles", list(-100, -50), 20),
			/obj/item/reagent_containers/snacks/spagetti = good_data("Raw Speghetti", list(-100, -50), 23),
			/obj/item/reagent_containers/snacks/pastatomato = good_data("Spaghetti Pasta", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/meatballspagetti = good_data("Spaghetti & Meatballs", list(-100, -50), 35),
			/obj/item/reagent_containers/snacks/spesslaw = good_data("Spesslaw", list(-100, -50), 45)
		),
		//Everything else that i dont care to sort
		"Culinary" = list(
			/obj/item/reagent_containers/snacks/boiledrice= good_data("Boiled Rice", list(-100, -50), 20),
			/obj/item/reagent_containers/snacks/ricepudding = good_data("Rice Pudding", list(-100, -50), 70),
			/obj/item/reagent_containers/snacks/beefcurry = good_data("Beef Curry", list(-100, -50), 200),
			/obj/item/reagent_containers/snacks/chickencurry = good_data("Poultry Curry", list(-100, -50), 220),
			/obj/item/reagent_containers/snacks/mashpotatoes = good_data("Mashed Potatoes", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/katsudon = good_data("Katsudon", list(-100, -50), 160),
			/obj/item/reagent_containers/snacks/carrotfries = good_data("Carrot Fries", list(-100, -50), 20),
			/obj/item/reagent_containers/snacks/candiedapple = good_data("Candied Apple", list(-100, -50), 80),
			/obj/item/reagent_containers/snacks/plumphelmetbiscuit = good_data("Plump Helmet Biscuit", list(-100, -50), 230),
			/obj/item/reagent_containers/snacks/chawanmushi = good_data("Chawanmushi", list(-100, -50), 230),
			/obj/item/reagent_containers/snacks/appletart = good_data("Appletart", list(-100, -50), 200),
			/obj/item/reagent_containers/snacks/tofurkey = good_data("Tofurkey", list(-100, -50), 300),
			/obj/item/reagent_containers/snacks/fishfingers = good_data("Fish Fingers", list(-100, -50), 140),
			/obj/item/reagent_containers/snacks/sashimi = good_data("Sashimi", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/eggplantparm = good_data("Eggplant Parmigiana", list(-100, -50), 80),
			/obj/item/reagent_containers/snacks/soylenviridians = good_data("Soylen Virdians", list(-100, -50), 50),
			/obj/item/reagent_containers/snacks/tofukabob = good_data("Tofu-Kabob", list(-100, -50), 22),
			/obj/item/reagent_containers/snacks/monkeykabob = good_data("Meat-Kabob", list(-100, -50), 24),
			/obj/item/reagent_containers/snacks/cubancarp = good_data("Cuban Carp", list(-100, -50), 45),
			/obj/item/reagent_containers/snacks/popcorn = good_data("Popcorn", list(-100, -50), 11),
			/obj/item/reagent_containers/snacks/loadedbakedpotato = good_data("Loaded Baked Potato", list(-100, -50), 23),
			/obj/item/reagent_containers/snacks/fries = good_data("Fries", list(-100, -50), 12),
			/obj/item/reagent_containers/snacks/soydope = good_data("Soy Dope", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/cheesyfries = good_data("Chessy Fries", list(-100, -50), 22),
			/obj/item/reagent_containers/snacks/meatsteak = good_data("Meat Steak", list(-100, -50), 15),
			/obj/item/reagent_containers/snacks/chickensteak = good_data("Chicken Steak", list(-100, -50), 50),
			/obj/item/reagent_containers/snacks/roastchicken = good_data("Chicken Roast", list(-100, -50), 70),
			/obj/item/reagent_containers/snacks/friedchikin = good_data("Fried Poultry", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/tonkatsu = good_data("Tonkatsu", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/spacylibertyduff = good_data("Spacy Liberty Duff", list(-100, -50), 150),
			/obj/item/reagent_containers/snacks/enchiladas = good_data("Enchiladas", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/fishandchips = good_data("Fish And Chips", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/stewedsoymeat = good_data("Stewed Soy Meat", list(-100, -50), 100)
		)
	)

	hidden_inventory = list(
		"Exotic Culinary" = list(
			/obj/item/reagent_containers/snacks/honeybuns= good_data("Iced Honey Buns", list(-100, -50), 400),
			/obj/item/reagent_containers/snacks/chocolatepiece = good_data("Chocolate Piece", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/chocolatepiece/white = good_data("White Chocolate Piece", list(-100, -50), 200),
			/obj/item/reagent_containers/snacks/chocolatepiece/truffle = good_data("Chocolate Truffle", list(-100, -50), 200),
			/obj/item/reagent_containers/snacks/wingfangchu = good_data("Wing Fang Ch", list(-100, -50), 500),
			/obj/item/reagent_containers/snacks/amanitajelly = good_data("Amanita Jelly", list(-100, -50), 300),
			/obj/item/reagent_containers/snacks/monkeysdelight = good_data("Monkey's Delight", list(-100, -50), 700),
			/obj/item/reagent_containers/snacks/boiledslimecore = good_data("Boiled Slime Core", list(-100, -50), 800),
			/obj/item/reagent_containers/snacks/mint = good_data("Mint", list(-100, -50), 300),
			/obj/item/reagent_containers/snacks/dumplings = good_data("Dumplings", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/rofflewaffles = good_data("Roffle Waffles", list(-100, -50), 150)
		),
		"Exotic Bread" = list(
			/obj/item/reagent_containers/snacks/xenomeatbread = good_data("Xenomeatbread Loaf", list(-100, -50), 500),
			/obj/item/reagent_containers/snacks/xenomeatbreadslice = good_data("Xenomeatbread Slice", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/cookie = good_data("Cookie", list(-100, -50), 30),
			/obj/item/reagent_containers/snacks/chocolatepiece/truffle = good_data("Chocolate Truffle", list(-100, -50), 300),
			/obj/item/reagent_containers/snacks/donut = good_data("Donut", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/donut/jelly = good_data("Jelly Donut", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/donut/slimejelly = good_data("Slime Jelly Donut", list(-100, -50), 130),
			/obj/item/reagent_containers/snacks/donut/chaos= good_data("Chaos Donut", list(-100, -50), 400),
			/obj/item/reagent_containers/snacks/donut/cherryjelly = good_data("Cherry Jelly Donut", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/donut/stat_buff = good_data("Masterpiece Donut", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/xemeatpie = good_data("Xeno Pie", list(-100, -50), 150)
		),
		"Exotic Burger" = list(
			/obj/item/reagent_containers/snacks/kampferburger = good_data("Kampfer Burger", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/panzerburger = good_data("Panzer Burger", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/jagerburger = good_data("Jager Burger", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/seucheburger = good_data("Seuche Burger", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/bigroachburger = good_data("Big Roach Burger", list(-100, -50), 300),
			/obj/item/reagent_containers/snacks/fuhrerburger = good_data("Fuhrer Burger", list(-100, -50), 250),
			/obj/item/reagent_containers/snacks/kaiserburger = good_data("Kaiser Burger", list(-100, -50), 300),
			/obj/item/reagent_containers/snacks/roburger = good_data("Roburger", list(-100, -50), 600),
			/obj/item/reagent_containers/snacks/roburgerbig = good_data("Big Roburger", list(-100, -50), 500),
			/obj/item/reagent_containers/snacks/xenoburger = good_data("Xenoburger", list(-100, -50), 150),
			/obj/item/reagent_containers/snacks/clownburger = good_data("Clown Burger", list(-100, -50), 500),
			/obj/item/reagent_containers/snacks/mimeburger = good_data("Mime Burger", list(-100, -50), 500),
			/obj/item/reagent_containers/snacks/spellburger = good_data("Spell Burger", list(-100, -50), 500)
		),
		"Human Meat" = list(
			/obj/item/reagent_containers/snacks/human/kabob = good_data("Human Kabob", list(-100, -50), 120),
			/obj/item/reagent_containers/snacks/human = good_data("Human Burger", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/brainburger = good_data("Brain Burger", list(-100, -50), 700),
			/obj/item/reagent_containers/snacks/braincake = good_data("Brain Cake", list(-100, -50), 500),
			/obj/item/reagent_containers/snacks/braincakeslice = good_data("Brain Cake Slice", list(-100, -50), 100),
			/obj/item/reagent_containers/snacks/soylentgreen = good_data("Soylent Green", list(-100, -50), 400)
		),
		"Salad" = list(
			/obj/item/reagent_containers/snacks/aesirsalad = good_data("Aesir Salad", list(-100, -50), 300),
			/obj/item/reagent_containers/snacks/validsalad = good_data("Valid Salad", list(-100, -50), 300),
			/obj/item/reagent_containers/snacks/tossedsalad = good_data("Tossed Salad", list(-100, -50), 300)
		)
	)

	offer_types = list(
		/obj/item/soap = offer_data("Soap", 250, 2),
		/obj/item/reagent_containers/glass/rag = offer_data("Rag", 40, 5),
		/obj/item/reagent_containers/spray = offer_data("Spray Bottle", 40, 10),
		/obj/item/mop = offer_data("Mop", 150, 2),
		/obj/item/reagent_containers/snacks/grown = offer_data("spare grown food", 10, 120),
		/datum/reagent/organic/nutriment/flour = offer_data("flour bottle (60u)", 200, 3),
		/datum/reagent/organic/nutriment/rice = offer_data("rice bottle (60u)", 200, 3)
	)

