/datum/trade_station/station_ghostkitchen
	name_pool = list(
		"GK 'Spector'" = "Ghost Kitchen 'Spector': \"We got tons of orders that need filling, will take anything you can cook."
	)
	uid = "ghostkitchen"
	start_discovered = TRUE
	spawn_always = TRUE
	markup = COMMON_GOODS
	offer_limit = 20
	base_income = 1600
	wealth = 0
	secret_inv_threshold = 1000
	recommendation_threshold = 3000
	stations_recommended = list("mcronalds") //Alt way to get to it
	assortiment = list(
		"Non-Meals" = list(
			/obj/item/reagent_containers/food/snacks/rawcutlet = good_data("Raw Cutlet", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/cutlet = good_data("Cooked Cutlet", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/patty_raw = good_data("Raw Patty", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/patty = good_data("Cooked Patty", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/chickenbreast = good_data("Chicken Breast", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/rawmeatball = good_data("Raw Meatball", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/meatball = good_data("Meatball", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/chickenbreast = good_data("Chicken Breast", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/rawsticks = good_data("Raw Potato Sticks", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/tofubread = good_data("Tofubread", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/tofubreadslice = good_data("Tofubread Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/tofu = good_data("Tofu", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/stuffing = good_data("Stuffing", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/bacon = good_data("Bacon", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/hugemushroomslice = good_data("Mushroom Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/tomatomeat = good_data("Tomato Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sausage = good_data("Sausage", list(-2, -1))
		),
		"Egg-Based" = list(
			/obj/item/reagent_containers/food/snacks/egg = good_data("Egg", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/egg/clucker = good_data("Clucker Egg", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/chocolateegg = good_data("Chocolate Egg", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/baconeggs = good_data("Egg And Bacon", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/benedict = good_data("Egg Benedict", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/muffinegg = good_data("Muffin Egg Sandwich", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/friedegg = good_data("Fried Egg", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/boiledegg = good_data("Boiled Egg", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/omelette = good_data("Omelette Du Fromage", list(-2, -1))
		),
		"Breads" = list(
			/obj/item/reagent_containers/food/snacks/sliceable/bread = good_data("Bread Loaf", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/breadslice = good_data("Bread Slice", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/sliceable/creamcheesebread = good_data("Cream Cheese Bread", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/creamcheesebreadslice = good_data("Cream Cheese Bread Slice", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/sliceable/meatbread = good_data("Meatbread Loaf", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/meatbreadslice = good_data("Meatbread Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/bananabread = good_data("Banana-Nut Loaf", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/bananabreadslice = good_data("Banana-Nut Bread Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/butterbread = good_data("Buttered Toast", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/flatbread = good_data("Flatbread", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/medialuna = good_data("Croissantt", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/dough = good_data("Dough", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/flatdough = good_data("Rolled Dough", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/doughslice = good_data("Dough slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/bun = good_data("Bun", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/cinnamonroll = good_data("Cinnamonroll", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/dough = good_data("Dough", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/poppypretzel = good_data("Poppy Pretzel", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/cracker = good_data("Saltine", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/baguette = good_data("Baguette", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/jelliedtoast = good_data("Jillied Toast", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/jelliedtoast/cherry = good_data("Cherry Toast", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/jelliedtoast/slime = good_data("Slime Toast", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/muffin = good_data("Muffin", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/waffles = good_data("Waffles", list(-2, -1))
		),
		"Sandwich" = list(
			/obj/item/reagent_containers/food/snacks/sandwich = good_data("Sandwich", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/toastedsandwich = good_data("Toasted Sandwich", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/toasted_guild_sandwich = good_data("Deluxe Toasted Sandwich", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/grilledcheese = good_data("Grilled Cheese", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/blt = good_data("BLT", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/twobread = good_data("Two Bread", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/jellysandwich = good_data("Jelly Sandwich", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/jellysandwich/slime = good_data("Slime Jelly Sandwich", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/jellysandwich/cherry = good_data("Cherry Jelly Sandwich", list(-2,- 1))
		),
		"Cakes|Pies" = list(
			/obj/item/reagent_containers/food/snacks/sliceable/birthdaycake = good_data("Birthday Cake", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/birthdaycakeslice = good_data("Birthday Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/applecake = good_data("Apple Cake", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/applecakeslice = good_data("Apple Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/carrotcake = good_data("Carrot Cake", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/carrotcakeslice = good_data("Carrot Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/cheesecake = good_data("Cheese Cake", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/cheesecakeslice = good_data("Cheese Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/plaincake = good_data("Vanilla Cake", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/plaincakeslice = good_data("Vanilla Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/orangecake = good_data("Orange Cake", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/orangecakeslice = good_data("Orange Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/limecake = good_data("Lime Cake", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/limecakeslice = good_data("Lime Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/lemoncake = good_data("Lemon Cake", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/lemoncakeslice = good_data("Lemon Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/chocolatecake = good_data("Chocolate Cake", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/chocolatecakeslice = good_data("Chocolate Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/brownie = good_data("Brownie Tray", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/brownieslice = good_data("Brownie Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/meatpie = good_data("Meat Pie", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/tofupie = good_data("Tofu Pie", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/amanita_pie = good_data("Amanita Pie", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/plump_pie = good_data("Plump Pie", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/applepie = good_data("Apple Piee", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/cherrypie = good_data("Cherry Pie", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/berryclafoutis = good_data("Berry Clafoutis Pie", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/pie = good_data("Pie", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/brownieslice = good_data("Brownie Slice", list(-2, -1))
		),
		"Pizza!" = list(
			/obj/item/reagent_containers/food/snacks/sliceable/pizza/margherita = good_data("Margherita Pizza", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/sliceable/pizza/meatpizza = good_data("Meat Pizza", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/pizza/mushroompizza = good_data("Mushroom Pizza", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/pizza/vegetablepizza = good_data("Vegetable Pizza", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/sliceable/pizza/hawaiianpizza = good_data("Hawaiian Pizza", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/hawaiianpizzaslice = good_data("Hawaiian Pizza Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/vegetablepizzaslice = good_data("Vegetable Pizza Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/mushroompizzaslice = good_data("Mushroom Pizza Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/meatpizzaslice = good_data("Meat Pizza Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/margheritaslice = good_data("Margherita Pizza Slice", list(-2, -1))
		),
		"Stews" = list(
			/obj/item/reagent_containers/food/snacks/meatballsoup = good_data("Meatball Soup", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/slimesoup = good_data("Slime Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/bloodsoup = good_data("Vampirer Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/clownstears = good_data("Clown's Tears", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/vegetablesoup = good_data("Vegetable Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/nettlesoup = good_data("Nettle Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/mysterysoup = good_data("Vegetable Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/vegetablesoup = good_data("Mystery Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/wishsoup = good_data("Wish Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/tomatosoup = good_data("Tomato Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/mushroomsoup = good_data("Chantrelle Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/beetsoup = good_data("Beet Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/milosoup = good_data("Milo Soup", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/stew = good_data("Stew", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/hotchili = good_data("Hot Chili", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/coldchili = good_data("Cold Chili", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/bearchili = good_data("Bear Meat Chili", list(-2, -1))
		),
		"Dairy" = list(
			/obj/item/reagent_containers/food/snacks/sliceable/cheesewheel = good_data("Cheesewheel", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/cheesewedge = good_data("Cheese Wedge", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/sliceable/butterstick = good_data("Butter Stick", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/butterslice = good_data("Butter Slice", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/icecream = good_data("Icecream", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/chocoicecream = good_data("Chocolate Icecream", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/strawberryicecream = good_data("Strawberry Icecream", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/icecreamsandwich = good_data("Icecream Sandwich", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/strawberrysandwich = good_data("Strawberry Icecream Sandwich", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/honeypudding = good_data("Honey Pudding", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/honey_icecream = good_data("Honey Icecream", list(-2, -1))
		),
		"Burger" = list(
			/obj/item/reagent_containers/food/snacks/cheeseburger = good_data("Cheese Burger", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/monkeyburger = good_data("Monkey Meat Buger", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/fishburger = good_data("Fillet-O-Carp Sandwich", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/baconburger = good_data("Bacon Burger", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/chickenburger = good_data("Poultry Fried Steak Sandwich", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/tofuburger = good_data("Tofu Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/bigbiteburger = good_data("Big Bite Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/superbiteburger = good_data("Super Bite Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/jellyburger = good_data("Jelly Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/jellyburger/slime = good_data("Slime Jelly Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/jellyburger/cherry = good_data("Cherry Jelly Burger", list(-2, -1))
		),
		"Speghetti" = list(
			/obj/item/reagent_containers/food/snacks/boiledspagetti= good_data("Boiled Noodles", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/spagetti = good_data("Speghetti", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/pastatomato = good_data("Spaghetti Pasta", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/meatballspagetti = good_data("Spaghetti & Meatballs", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/spesslaw = good_data("Spesslaw", list(-2,- 1))
		),
		//Everything else that i dont care to sort
		"Culinary" = list(
			/obj/item/reagent_containers/food/snacks/boiledrice= good_data("Boiled Rice", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/ricepudding = good_data("Rice Pudding", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/beefcurry = good_data("Beef Curry", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/chickencurry = good_data("Poultry Curry", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/mashpotatoes = good_data("Mashed Potatoes", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/katsudon = good_data("Katsudon", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/carrotfries = good_data("Carrot Fries", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/candiedapple = good_data("Candied Apple", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/plumphelmetbiscuit = good_data("Plump Helmet Biscuit", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/chawanmushi = good_data("Chawanmushi", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/appletart = good_data("Appletart", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/tofurkey = good_data("Tofurkey", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/fishfingers = good_data("Fish Fingers", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/sashimi = good_data("Sashimi", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/eggplantparm = good_data("Eggplant Parmigiana", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/soylenviridians = good_data("Soylen Virdians", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/tofukabob = good_data("Tofu-Kabob", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/monkeykabob = good_data("Meat-Kabob", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/cubancarp = good_data("Cuban Carp", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/popcorn = good_data("Popcorn", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/loadedbakedpotato = good_data("Loaded Baked Potato", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/fries = good_data("Fries", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/soydope = good_data("Soy Dope", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/cheesyfries = good_data("Chessy Fries", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/meatsteak = good_data("Meat Steak", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/chickensteak = good_data("Chicken Steak", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/roastchicken = good_data("Chicken Roast", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/friedchikin = good_data("Fried Poultry", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/tonkatsu = good_data("Tonkatsu", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/spacylibertyduff = good_data("Spacy Liberty Duff", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/enchiladas = good_data("Enchiladas", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/fishandchips = good_data("Fish And Chips", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/stewedsoymeat = good_data("Stewed Soy Meat", list(-2,- 1))
		)
	)

	secret_inventory = list(
		"Exotic Culinary" = list(
			/obj/item/reagent_containers/food/snacks/honeybuns= good_data("Iced Honey Buns", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/chocolatepiece = good_data("Chocolate Piece", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/chocolatepiece/white = good_data("White Chocolate Piece", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/chocolatepiece/truffle = good_data("Chocolate Truffle", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/wingfangchu = good_data("Wing Fang Ch", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/amanitajelly = good_data("Amanita Jelly", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/monkeysdelight = good_data("Monkey's Delight", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/boiledslimecore = good_data("Boiled Slime Core", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/mint = good_data("Mint", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/dumplings = good_data("Dumplings", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/rofflewaffles = good_data("Roffle Waffles", list(-2,- 1))
		),
		"Exotic Bread" = list(
			/obj/item/reagent_containers/food/snacks/sliceable/xenomeatbread = good_data("Xenomeatbread Loaf", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/xenomeatbreadslice = good_data("Xenomeatbread Slice", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/cookie = good_data("Cookie", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/chocolatepiece/truffle = good_data("Chocolate Truffle", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/donut = good_data("Donut", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/donut/jelly = good_data("Jelly Donut", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/donut/slimejelly = good_data("Slime Jelly Donut", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/donut/chaos= good_data("Choas Donut", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/donut/cherryjelly = good_data("Cherry Jelly Donut", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/donut/stat_buff = good_data("Masterpiece Donut", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/xemeatpie = good_data("Xeno Pie", list(-2,- 1))
		),
		"Exotic Burger" = list(
			/obj/item/reagent_containers/food/snacks/kampferburger = good_data("Kampfer Burger", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/panzerburger = good_data("Panzer Burger", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/jagerburger = good_data("Jager Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/seucheburger = good_data("Seuche Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/bigroachburger = good_data("Big Roach Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/fuhrerburger = good_data("Fuhrer Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/kaiserburger = good_data("Kaiser Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/donut/slimejelly = good_data("Slime Jelly Donut", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/donut/chaos = good_data("Choas Donut", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/donut/cherryjelly = good_data("Cherry Jelly Donut", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/donut/stat_buff = good_data("Masterpiece Donut", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/xemeatpie = good_data("Xeno Pie", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/roburger = good_data("Roburger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/roburgerbig = good_data("Big Roburger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/xenoburger = good_data("Xenoburger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/clownburger = good_data("Clown Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/mimeburger = good_data("Mime Burger", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/spellburger = good_data("Spell Burger", list(-2, -1))
		),
		"Human Meat" = list(
			/obj/item/reagent_containers/food/snacks/human/kabob = good_data("Human Kabob", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/human = good_data("Human Burger", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/brainburger = good_data("Brain Burger", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/sliceable/braincake = good_data("Brain Cake", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/braincakeslice = good_data("Brain Cake Slice", list(-2, -1)),
			/obj/item/reagent_containers/food/snacks/soylentgreen = good_data("Soylent Green", list(-2, -1))
		),
		"Salad" = list(
			/obj/item/reagent_containers/food/snacks/aesirsalad = good_data("Aesir Salad", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/validsalad = good_data("Valid Salad", list(-2,- 1)),
			/obj/item/reagent_containers/food/snacks/tossedsalad = good_data("Tossed Salad", list(-2,- 1))
		)
	)

	offer_types = list(
		/obj/item/soap = offer_data("Soap", 250, 2),
		/obj/item/reagent_containers/glass/rag = offer_data("Rag", 40, 5),
		/obj/item/reagent_containers/spray = offer_data("Spray Bottle", 40, 10),
		/obj/item/mop = offer_data("Mop", 150, 2),
		/obj/item/reagent_containers/food/snacks/grown = offer_data("spare grown food", 10, 120)
	)

