/obj/item/modular_computer/wrist/install_default_hardware()
	..()
	network_card = new network_card_type(src)
	hard_drive = new hard_drive_type(src)
	processor_unit = new processor_unit_type(src)
	card_slot = new /obj/item/computer_hardware/card_slot(src)
	cell = new /obj/item/cell/small/moebius/pda(src)
	gps_sensor= new /obj/item/computer_hardware/gps_sensor(src)
	led = new /obj/item/computer_hardware/led(src)
	if(scanner_type)
		scanner = new scanner_type(src)
	if(tesla_link_type)
		tesla_link = new tesla_link_type(src)

/obj/item/modular_computer/wrist/install_default_programs()
	..()

	hard_drive.store_file(new /datum/computer_file/program/chatclient())
	hard_drive.store_file(new /datum/computer_file/program/email_client())
	hard_drive.store_file(new /datum/computer_file/program/crew_manifest())
	hard_drive.store_file(new /datum/computer_file/program/wordprocessor())
	hard_drive.store_file(new /datum/computer_file/program/records())
	hard_drive.store_file(new /datum/computer_file/program/bounty_board_app())
	hard_drive.store_file(new /datum/computer_file/program/trade/order())
