/obj/structure/closet/secure_closet/reinforced/commander
	name = "militia commander's locker"
	req_access = list(access_hos)
	icon_state = "mc"

/obj/structure/closet/secure_closet/reinforced/commander/populate_contents()
	if(prob(50))
		new /obj/item/ammo_magazine/hrifle/lethal(src)
	else
		new /obj/item/ammo_magazine/hrifle/hv(src)
	new /obj/item/ammo_magazine/hrifle/lethal(src)
	new /obj/item/weapon/storage/backpack/satchel/ironhammer(src)
	new /obj/item/clothing/head/rank/milcom/beret(src)
	new /obj/item/clothing/head/rank/milcom(src)
	new /obj/item/clothing/mask/gas(src)
	new /obj/item/clothing/suit/armor/flackvest/commander(src)
	new /obj/item/clothing/suit/armor/commander/militia(src)
	new /obj/item/clothing/under/rank/commander(src)
	new /obj/item/clothing/under/rank/commander/formal(src)
	new /obj/item/clothing/head/rank/mcommander(src)
	new /obj/item/clothing/head/rank/instructor_hat(src)
	new /obj/item/weapon/gun/projectile/automatic/omnirifle/scoped(src)
	new /obj/item/clothing/glasses/ballistic(src)
	new /obj/item/weapon/storage/belt/security(src)
	new /obj/item/clothing/gloves/stungloves(src)
	new /obj/item/clothing/accessory/armband/militia(src)
	new /obj/item/weapon/gun/projectile/lamia/scoped/dark(src)
	new /obj/item/ammo_magazine/kurtz(src)
	new /obj/item/ammo_magazine/kurtz(src)
	new /obj/item/ammo_magazine/kurtz(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/weapon/melee/telebaton(src)
	new /obj/item/weapon/storage/pouch/ammo(src)
	new /obj/item/clothing/suit/greatcoat/ihc/bmc(src)
	new /obj/item/clothing/suit/greatcoat/ihc/bmc_cloaked(src)
	new /obj/item/weapon/storage/pouch/baton_holster(src)
	new /obj/item/weapon/storage/firstaid/ifak(src)
	if(prob(50))
		new /obj/item/weapon/storage/backpack/security(src)
	else
		new /obj/item/weapon/storage/backpack/militia(src)

/obj/structure/closet/secure_closet/armorer
	name = "sergeant's locker"
	req_access = list(access_armory)
	icon_state = "armorer"

/obj/structure/closet/secure_closet/armorer/populate_contents()
	if(prob(55))
		new /obj/item/clothing/head/helmet/ballistic/militia(src)
	else
		new /obj/item/clothing/head/helmet/ballistic/green(src)
	if(prob(50))
		new /obj/item/weapon/storage/backpack/military(src)
	else
		new /obj/item/weapon/storage/backpack/security(src)
	if(prob(50))
		new /obj/item/weapon/gun/projectile/automatic/omnirifle/standard(src)
	else
		new /obj/item/weapon/gun/projectile/automatic/omnirifle/scoped(src)
	if(prob(50))
		new /obj/item/ammo_magazine/hrifle/lethal(src)
	else
		new /obj/item/ammo_magazine/hrifle/hv(src)
	if(prob(50))
		new /obj/item/weapon/gun/projectile/colt/ten/dark(src)
		new /obj/item/ammo_magazine/magnum(src)
		new /obj/item/ammo_magazine/magnum/lethal(src)
	else
		new /obj/item/weapon/gun/projectile/lamia/dark(src)
		new /obj/item/ammo_magazine/kurtz(src)
		new /obj/item/ammo_magazine/kurtz/lethal(src)
	new /obj/item/ammo_magazine/hrifle(src)
	new /obj/item/clothing/under/rank/armorer(src)
	new /obj/item/clothing/head/rank/armorer/beret(src)
	new /obj/item/clothing/head/rank/instructor_hat(src)
	new /obj/item/clothing/accessory/dogtags(src)
	new /obj/item/clothing/under/instructor(src)
	new /obj/item/clothing/head/rank/armorer/cap(src)
	new /obj/item/weapon/storage/belt/security(src)
	new /obj/item/clothing/mask/gas(src)
	new /obj/item/weapon/storage/pouch/baton_holster(src)
	new /obj/item/clothing/accessory/holster/leg(src)
	new /obj/item/weapon/melee/telebaton(src)
	new /obj/item/weapon/storage/pouch/ammo(src)
	new /obj/item/clothing/glasses/ballistic(src)
	new /obj/item/clothing/accessory/armband/militia(src)
	new /obj/item/clothing/under/rank/armorer/green(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)
	new /obj/item/clothing/suit/armor/flackvest/militia(src)
	new /obj/item/weapon/storage/firstaid/ifak(src)

/obj/structure/closet/secure_closet/personal/trooper
	name = "blackshield trooper's locker"
	req_access = list(access_hos)
	access_occupy = list(access_brig)
	icon_state = "trooper"

/obj/structure/closet/secure_closet/personal/trooper/populate_contents()
	if(prob(50))
		new /obj/item/clothing/suit/armor/platecarrier(src)
	else
		new /obj/item/clothing/suit/armor/platecarrier/militia(src)
	if(prob(50))
		new /obj/item/clothing/head/helmet/ballistic/militia(src)
	else
		new /obj/item/clothing/head/helmet/ballistic(src)
	switch(pick("omni", "hustler", "sts"))
		if ("omni")
			new /obj/item/weapon/gun/projectile/automatic/omnirifle/standard(src)
		if ("hustler")
			new /obj/item/weapon/gun/projectile/automatic/omnirifle(src)
		if ("sts")
			new /obj/item/weapon/gun/projectile/automatic/sts/hrifle(src)
			new /obj/item/clothing/under/shorts/khaki(src)
			new /obj/item/clothing/glasses/aviator(src)
	if(prob(50))
		new /obj/item/weapon/storage/pouch/medium_generic(src)
	else
		new /obj/item/weapon/storage/pouch/ammo(src)
	if(prob(50))
		new /obj/item/clothing/under/rank/trooper/green(src)
	else
		new /obj/item/clothing/under/rank/trooper/tan(src)
	if(prob(50))
		new /obj/item/weapon/storage/backpack/security(src)
	else
		new /obj/item/weapon/storage/backpack/militia(src)
	if(prob(50))
		new /obj/item/weapon/storage/belt/webbing/black(src)
	else
		new /obj/item/weapon/storage/belt/webbing/green(src)
	if(prob(50))
		new /obj/item/weapon/gun/projectile/colt/ten/dark(src)
		new /obj/item/ammo_magazine/magnum(src)
		new /obj/item/ammo_magazine/magnum/lethal(src)
	else
		new /obj/item/weapon/gun/projectile/ladon(src)
		new /obj/item/ammo_magazine/magnum(src)
		new /obj/item/ammo_magazine/magnum/lethal(src)
	new /obj/item/ammo_magazine/hrifle(src)
	new /obj/item/ammo_magazine/hrifle(src)
	new /obj/item/ammo_magazine/hrifle/lethal(src)
	new /obj/item/clothing/accessory/dogtags(src)
	new /obj/item/clothing/under/rank/trooper(src)
	new /obj/item/weapon/storage/backpack/satchel/ironhammer(src)
	new /obj/item/weapon/storage/belt/security(src)
	new /obj/item/clothing/mask/gas(src)
	new /obj/item/clothing/gloves/thick(src)
	new /obj/item/clothing/mask/balaclava/tactical(src)
	new /obj/item/weapon/storage/pouch/baton_holster(src)
	new /obj/item/clothing/accessory/holster/leg(src)
	new /obj/item/weapon/melee/telebaton(src)
	new /obj/item/clothing/glasses/ballistic(src)
	new /obj/item/clothing/accessory/armband/militia(src)
	new /obj/item/clothing/head/rank/trooper/beret(src)
	new /obj/item/clothing/head/rank/trooper/cap(src)
	new /obj/item/weapon/storage/firstaid/ifak(src)
	new /obj/item/clothing/suit/armor/commander/militia_overcoat(src)
	new /obj/item/weapon/grenade/smokebomb(src)
	new /obj/item/weapon/grenade/smokebomb(src)

/obj/structure/closet/secure_closet/personal/corpsman
	name = "blackshield medical corpsman locker"
	req_access = list(access_medspec)
	icon_state = "corpsman"
/obj/item/clothing/glasses/hud/health
/obj/structure/closet/secure_closet/personal/corpsman/populate_contents()
	new /obj/item/weapon/storage/belt/webbing/black(src)
	if(prob(60))
		new /obj/item/weapon/gun/projectile/automatic/omnirifle/omnicarbine(src)
	else
		new /obj/item/weapon/gun/projectile/automatic/omnirifle/omnicarbine/rds(src)
	if(prob(50))
		new /obj/item/weapon/storage/backpack/military(src)
	else
		new /obj/item/weapon/storage/backpack/security(src)
	if(prob(50))
		new /obj/item/ammo_magazine/hrifle/lethal(src)
	else
		new /obj/item/ammo_magazine/hrifle/hv(src)
	if(prob(50))
		new /obj/item/weapon/gun/projectile/colt/ten/dark(src)
		new /obj/item/ammo_magazine/magnum(src)
		new /obj/item/ammo_magazine/magnum/lethal(src)
	else
		new /obj/item/weapon/gun/projectile/ladon(src)
		new /obj/item/ammo_magazine/magnum(src)
		new /obj/item/ammo_magazine/magnum/lethal(src)
	new /obj/item/ammo_magazine/hrifle(src)
	new /obj/item/clothing/suit/armor/platecarrier/corpsman(src)
	new /obj/item/clothing/mask/gas(src)
	new /obj/item/clothing/under/rank/corpsman(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/clothing/mask/balaclava/tactical(src)
	new /obj/item/clothing/accessory/dogtags(src)
	new /obj/item/clothing/accessory/holster/leg(src)
	new /obj/item/weapon/storage/belt/medical/emt(src)
	new /obj/item/device/scanner/health(src)
	new /obj/item/clothing/glasses/hud/health(src)
	new /obj/item/clothing/accessory/armband/corpsman(src)
	new /obj/item/clothing/head/rank/corpsman/beret(src)
	new /obj/item/clothing/head/rank/corpsman/cap(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/clothing/gloves/latex(src)
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline(src)
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin(src)
	new /obj/item/weapon/storage/firstaid/adv(src)
	new /obj/item/weapon/storage/firstaid/ifak(src)
	new /obj/item/weapon/storage/pill_bottle/tramadol(src)

/obj/structure/closet/secure_closet/militia/armor
	name = "blackshield armor locker"
	req_access = list(access_brig)
	icon_state = "trooper"

/obj/structure/closet/secure_closet/militia/armor/populate_contents()
	if(prob(60))
		new /obj/item/clothing/suit/armor/flackvest(src)
	else
		new /obj/item/clothing/suit/armor/flackvest/green(src)
	new /obj/item/clothing/suit/armor/platecarrier(src)
	if(prob(50))
		new /obj/item/clothing/head/helmet/ballistic/militia(src)
	else
		new /obj/item/clothing/head/helmet/ballistic/green(src)
	new /obj/item/clothing/suit/armor/platecarrier(src)
	if(prob(50))
		new /obj/item/clothing/head/helmet/ballistic(src)
	else
		new /obj/item/clothing/head/helmet/ballistic/tan(src)
	new /obj/item/clothing/suit/armor/platecarrier(src)
	if(prob(50))
		new /obj/item/clothing/suit/armor/platecarrier/militia(src)
	else
		new /obj/item/clothing/suit/armor/platecarrier/tan(src)
	new /obj/item/clothing/suit/armor/platecarrier/militia(src)
	new /obj/item/clothing/suit/armor/flackvest(src)
	new /obj/item/clothing/suit/armor/flackvest/militia(src)
	new /obj/item/clothing/head/helmet/ballistic(src)
	new /obj/item/clothing/head/helmet/ballistic(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)
	new /obj/item/weapon/storage/belt/webbing(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)
	new /obj/item/weapon/storage/belt/webbing/green(src)
	new /obj/item/weapon/storage/belt/webbing(src)
