/obj/structure/closet/secure_closet/reinforced/commander
	name = "blackshield commander's locker"
	req_access = list(access_hos)
	icon_state = "mc"

/obj/structure/closet/secure_closet/reinforced/commander/populate_contents()
	new /obj/item/weapon/gun/projectile/automatic/omnirifle/scoped(src)
	new /obj/item/ammo_magazine/heavy_rifle_408/lethal(src)
	new /obj/item/ammo_magazine/heavy_rifle_408/lethal(src)
	new /obj/item/ammo_magazine/heavy_rifle_408/lethal(src)
	new /obj/item/weapon/gun/projectile/lamia/scoped/dark(src)
	new /obj/item/ammo_magazine/kurtz_50(src)
	new /obj/item/ammo_magazine/kurtz_50(src)
	new /obj/item/ammo_magazine/kurtz_50(src)
	new /obj/item/weapon/melee/telebaton(src)
	new /obj/item/weapon/tool/knife/tacknife(src)
	new /obj/item/weapon/tool/disciplinary_action(src)
	new /obj/item/weapon/tool/fireaxe/militia_tomahawk(src)
	new /obj/item/clothing/accessory/patches/blackshield_commander(src)
	new /obj/item/clothing/accessory/holster/hip(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/clothing/head/rank/milcom/beret(src)
	new /obj/item/clothing/head/rank/milcom(src)
	new /obj/item/clothing/mask/gas(src)
	new /obj/item/clothing/gloves/stungloves(src)
	new /obj/item/clothing/suit/armor/flackvest/commander(src)
	new /obj/item/clothing/suit/armor/commander/militia(src)
	new /obj/item/clothing/suit/greatcoat/ihc/bmc(src)
	new /obj/item/clothing/suit/greatcoat/ihc/bmc_cloaked(src)
	new /obj/item/weapon/storage/pouch/ammo(src)
	new /obj/item/weapon/storage/pouch/baton_holster(src)
	new /obj/item/weapon/storage/firstaid/ifak(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)
	if(prob(50))
		new /obj/item/weapon/storage/backpack/satchel/ironhammer(src)
	else
		new /obj/item/weapon/storage/backpack/militia(src)
	new /obj/item/weapon/storage/box/commanderuniform(src)
	if(prob(5))
		new /obj/random/rations/crayon(src)

/obj/structure/closet/secure_closet/armorer
	name = "sergeant's locker"
	req_access = list(access_armory)
	icon_state = "armorer"

/obj/structure/closet/secure_closet/armorer/populate_contents()
	new /obj/item/weapon/gun/projectile/automatic/sts/rifle/blackshield(src)
	new /obj/item/ammo_magazine/speed_loader_rifle_75(src)
	new /obj/item/ammo_magazine/speed_loader_rifle_75(src)
	new /obj/item/ammo_magazine/speed_loader_rifle_75(src)
	new /obj/item/ammo_magazine/speed_loader_rifle_75(src)
	if(prob(60))
		new /obj/item/weapon/gun/projectile/colt/ten/dark(src)
		new /obj/item/ammo_magazine/magnum_40/lethal(src)
		new /obj/item/ammo_magazine/magnum_40/lethal(src)
	else
		new /obj/item/weapon/gun/projectile/lamia/dark(src)
		new /obj/item/ammo_magazine/kurtz_50/lethal(src)
		new /obj/item/ammo_magazine/kurtz_50/lethal(src)
	new /obj/item/weapon/melee/telebaton(src)
	new /obj/item/weapon/tool/knife/tacknife(src)
	new /obj/item/weapon/tool/fireaxe/militia_tomahawk(src)
	new /obj/item/clothing/accessory/patches/blackshield_sergeant(src)
	new /obj/item/clothing/accessory/holster/leg(src)
	new /obj/item/clothing/mask/gas(src)
	new /obj/item/clothing/gloves/thick(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/clothing/head/rank/armorer/beret(src)
	new /obj/item/clothing/head/rank/armorer/cap(src)
	new /obj/item/clothing/suit/armor/flackvest/militia(src)
	new /obj/item/clothing/under/rank/armorer(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)
	if(prob(50))
		new /obj/item/weapon/storage/backpack/satchel/ironhammer(src)
	else
		new /obj/item/weapon/storage/backpack/militia(src)
	new /obj/item/weapon/storage/pouch/baton_holster(src)
	new /obj/item/weapon/storage/pouch/ammo(src)
	new /obj/item/weapon/storage/firstaid/ifak(src)
	new /obj/item/weapon/storage/box/sergeantuniform(src)
	if(prob(5))
		new /obj/random/rations/crayon(src)

/obj/structure/closet/secure_closet/personal/trooper
	name = "blackshield trooper's locker"
	req_access = list(access_hos)
	access_occupy = list(access_brig)
	icon_state = "trooper"

/obj/structure/closet/secure_closet/personal/trooper/populate_contents()
	new /obj/item/weapon/gun/projectile/boltgun(src)
	new /obj/item/ammo_magazine/rifle_75(src)
	new /obj/item/ammo_magazine/rifle_75(src)
	if(prob(80))
		new /obj/item/weapon/gun/projectile/colt/ten/dark(src)
		new /obj/item/ammo_magazine/magnum_40/lethal(src)
		new /obj/item/ammo_magazine/magnum_40/lethal(src)
	else
		new /obj/item/weapon/gun/projectile/lamia/dark(src)
		new /obj/item/ammo_magazine/kurtz_50/lethal(src)
		new /obj/item/ammo_magazine/kurtz_50/lethal(src)
	new /obj/item/weapon/melee/telebaton(src)
	new /obj/item/weapon/tool/knife/tacknife(src)
	new /obj/item/weapon/tool/fireaxe/militia_tomahawk(src)
	new /obj/item/clothing/accessory/holster/leg(src)
	new /obj/item/clothing/accessory/patches/blackshield_trooper(src)
	new /obj/item/clothing/mask/gas(src)
	new /obj/item/clothing/mask/balaclava/tactical(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/clothing/head/rank/trooper/beret(src)
	new /obj/item/clothing/head/rank/trooper/cap(src)
	new /obj/item/clothing/glasses/ballistic(src)
	new /obj/item/clothing/suit/armor/platecarrier/militia(src)
	new /obj/item/clothing/gloves/thick(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)
	if(prob(50))
		new /obj/item/weapon/storage/backpack/satchel/ironhammer(src)
	else
		new /obj/item/weapon/storage/backpack/militia(src)
	new /obj/item/weapon/storage/pouch/ammo(src)
	new /obj/item/weapon/storage/pouch/baton_holster(src)
	new /obj/item/weapon/storage/firstaid/ifak(src)
	new /obj/item/weapon/storage/box/trooperuniform(src)
	if(prob(5))
		new /obj/random/rations/crayon(src)

/obj/structure/closet/secure_closet/personal/corpsman
	name = "blackshield medical corpsman locker"
	req_access = list(access_medspec)
	icon_state = "corpsman"

/obj/structure/closet/secure_closet/personal/corpsman/populate_contents()
	new /obj/item/weapon/gun/projectile/boltgun(src)
	new /obj/item/ammo_magazine/speed_loader_rifle_75(src)
	new /obj/item/ammo_magazine/speed_loader_rifle_75(src)
	new /obj/item/ammo_magazine/speed_loader_rifle_75(src)
	new /obj/item/ammo_magazine/speed_loader_rifle_75(src)
	new /obj/item/weapon/gun/projectile/colt/ten/dark(src)
	new /obj/item/ammo_magazine/magnum_40/lethal(src)
	new /obj/item/ammo_magazine/magnum_40/lethal(src)
	new /obj/item/roller(src)
	new /obj/item/device/scanner/health(src)
	new /obj/item/weapon/tool/knife/tacknife(src)
	new /obj/item/weapon/tool/fireaxe/militia_tomahawk(src)
	new /obj/item/clothing/accessory/patches/blackshield_corpsman(src)
	new /obj/item/clothing/accessory/holster/leg(src)
	new /obj/item/clothing/glasses/hud/health(src)
	new /obj/item/clothing/mask/gas(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/clothing/head/rank/corpsman/beret(src)
	new /obj/item/clothing/head/rank/corpsman/cap(src)
	new /obj/item/clothing/suit/armor/platecarrier/corpsman(src)
	new /obj/item/clothing/under/rank/corpsman(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)
	if(prob(40))
		new /obj/item/weapon/storage/backpack/militia(src)
	else
		new /obj/item/weapon/storage/backpack/duffelbag
	new /obj/item/weapon/storage/pouch/medical_supply
	new /obj/item/weapon/storage/firstaid/ifak(src)
	new /obj/item/weapon/storage/firstaid/adv(src)
	new /obj/item/weapon/storage/firstaid/combat(src)
	if(prob(25))
		new /obj/item/weapon/storage/firstaid/blackshield/large(src)
	new /obj/item/weapon/storage/box/trooperuniform(src)
	if(prob(5))
		new /obj/random/rations/crayon(src)

/obj/structure/closet/secure_closet/militia/armor
	name = "blackshield armor locker"
	req_access = list(access_brig)
	icon_state = "trooper"

/obj/structure/closet/secure_closet/militia/armor/populate_contents()
	new /obj/item/clothing/head/helmet/ballistic/green(src)
	new /obj/item/clothing/head/helmet/ballistic/green(src)
	new /obj/item/clothing/suit/armor/platecarrier/green(src)
	new /obj/item/clothing/suit/armor/platecarrier/green(src)
	new /obj/item/weapon/storage/belt/webbing/green(src)
	new /obj/item/weapon/storage/belt/webbing/green(src)
	new /obj/item/clothing/head/helmet/ballistic/tan(src)
	new /obj/item/clothing/head/helmet/ballistic/tan(src)
	new /obj/item/clothing/suit/armor/platecarrier/tan(src)
	new /obj/item/clothing/suit/armor/platecarrier/tan(src)
	new /obj/item/weapon/storage/belt/webbing(src)
	new /obj/item/weapon/storage/belt/webbing(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/clothing/head/helmet/ballistic/militia(src)
	new /obj/item/clothing/suit/armor/platecarrier/militia(src)
	new /obj/item/clothing/suit/armor/platecarrier/militia(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)
	new /obj/item/weapon/storage/belt/webbing/black(src)